---
version: "2"
services:
  example:
    build: .
    depends_on:
      - example-db
    volumes:
      - .:/src
      - ~/.m2/repository:/root/.m2/repository
    ports:
      - 8080:8080
      - 5005:5005
    restart: always
    privileged: true
    stdin_open: true
    tty: true
  example-db:
    image: postgres:17-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
  pg-admin:
    image: thajeztah/pgadmin4
    depends_on:
      - example-db
    restart: always
    ports:
      - 5050:5050
volumes:
  m2-cache: null
